---
version: "3"
services:
  nginx:
    image: trafex/alpine-nginx-php7
    ports:
      - "80:8080"
    volumes:
      - ./php/:/var/www/html/
      - ./nginx/:/var/www/html/
      - ./flag/flag.txt:/var/www/flag.txt